 function y=VariableCoolingTowerEquation(temp_water_out)
load CoeffCoolingTower;
Coeff=CoeffCoolingTower;




y=Coeff(1) + Coeff(2)*FRair + Coeff(3)*(FRair).^2 + ...
    Coeff(4)*(FRair).^3 + Coeff(5)*FRwater + Coeff(6)*FRair.*FRwater + ...
    Coeff(7)*(FRair).^2.*FRwater + Coeff(8)*(FRwater).^2 + Coeff(9)*FRair.*(FRwater).^2 +...
    Coeff(10)*(FRwater).^3 + Coeff(11)*Twb + Coeff(12)*FRair.*Twb + ...
    Coeff(13)*(FRair).^2.*Twb + Coeff(14)*FRwater.*Twb +...
    Coeff(15)*FRair.*FRwater.*Twb + Coeff(16)*(FRwater).^2.*Twb +...
    Coeff(17)*(Twb).^2 + Coeff(18)*FRair.*(Twb).^2 +...
    Coeff(19)*FRwater.*(Twb).^2 + Coeff(20)*(Twb).^3 + Coeff(21)*Tr +...
    Coeff(22)*FRair.*Tr + Coeff(23)*(FRair).^2.*Tr +...
    Coeff(24)*FRwater.*Tr + Coeff(25)*FRair.*FRwater.*Tr +...
    Coeff(26)*(FRwater).^2.*Tr + Coeff(27)*Twb.*Tr +...
    Coeff(28)*FRair.*Twb.*Tr + Coeff(29)*FRwater.*Twb.*Tr +...
    Coeff(30)*(Twb).^2.*Tr + Coeff(31)*(Tr).^2 + Coeff(32)*FRair.*(Tr).^2 +...
    Coeff(33)*FRwater*(Tr).^2 + Coeff(34)*Twb.*(Tr).^2 + Coeff(35)*(Tr).^3+Twb;
    end